application: stridesforshelter

version: 1 
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /script
  static_dir: script
  
- url: /images
  static_dir: images

- url: /.*
  script: requests.py
